<?php
/**
 * Implements hook_menu().
 */
function new_menu() {
	$items = array();

    $items['my-page'] = array(
	    'title' 		  	=> 'Home Page',
	    'page callback'   	=> 'my_home_page',
	    'access arguments' 	=> array('access homepage'),
	  );

  return $items;
}

/**
 * Implements hook_block_view().
 */

function new_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'text':
    	if (user_access('access content')){
      $block['subject'] = t('Title of free block');
      $block['content'] = array(
      		'#markup' 	=> t('Free text, text free'),
      	);
      		}
  		else {
  		$block['subject'] = t('Access to view this content is denied.');
      	$block['content'] = t(' ');
  		}
      return $block;
      break;
  }
  
}

/**
 * Implements hook_block_info().
 */

function new_block_info($delta = '') {
	$blocks['text'] = array(
		'info'  => t('Text example'),
		'cache' => DRUPAL_NO_CACHE,
		);
	return $blocks;
}


/**
 * Implements hook_permission().
 */

function new_permission() {
	return array(
		'access content'  => array(
			),
		'access homepage' => array(
			'title'		  => t('Home page view'),
			'description' => t('View home page'),
			),
		);
}

/**
 * Implements hook_init().
 */

function new_init() {
	if (drupal_is_front_page()) {
		drupal_add_css(drupal_get_path('module', 'new') . '/new.css');
	}
}

/**
 * Implements hook_node_view().
 */
function new_node_view($node, $view_mode, $langcode){
	$node->content['my_add_field'] = array(
		'#markup' => t('<h4 align="right">I am a hook node view</h4>'),
		'#weight' => 20,
		);
}

/**
 * Function my_home_page
 */
function my_home_page() {
	return t('Hello! This is first drupal site.');
}